[project]
org-name = "shan1024"
version = "0.1.1"
license = "Apache-2.0"
authors = ["shan1024"]
repository = "https://github.com/Shan1024/chalk"
keywords = ["chalk", "color", "colors", "terminal", "console", "ansi"]
